---
# Update apt
- name: Update and upgrade apt packages
  become: true  
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600

# Install software required for all environments
- name: Install basic software
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - vim
      - wget
      - git
      - python3
      - python3-pip
      - python3-venv
      - bc