---
- name: Add Telegraf repository key
  become: true
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    keyring: /etc/apt/trusted.gpg.d/telegraf.gpg
    state: present

- name: Add influx deb repository
  become: true
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian bookworm stable"
    filename: influxdb
    state: present
    update_cache: yes
    