---
- name: Add Grafana APT key
  become: true
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  become: true
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present