---
- name: Create /opt/projects directory
  become: true
  ansible.builtin.file:
    path: /opt/projects
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"
    mode: '0755'

- name: Clone pms5003-python
  git:
    repo: https://github.com/pimoroni/pms5003-python.git
    dest: /opt/projects/pms5003-sensor
    clone: yes
    update: yes

- name: Install pms5003-python
  ansible.builtin.shell: ./install.sh -f >> install_log.txt     
  args:
    chdir: /opt/projects/pms5003-sensor/