---
# - name: Clone pi-pms5003-air-quality-sensor
#   git:
#     repo: https://github.com/paulkamer/pi-pms5003-air-quality-sensor.git
#     dest: /opt/projects/pms5003-app
#     clone: yes
#     update: yes

- name: Synchronize local Git repo to remote
  ansible.posix.synchronize:
    src: "../../../../"
    dest: "/opt/projects/pms5003-app"
    rsync_opts:
      - "--exclude=.git,ansible,venv"

- name: Install Python dependencies from requirements.txt
  pip:
    requirements: "/opt/projects/pms5003-app/requirements.txt"
    virtualenv: "~/.virtualenvs/pimoroni"
    virtualenv_command: "python -m venv"
    virtualenv_python: python